configs:
  # general optimization parameters:
  batch_size: 64
  gibbs_samples: 1
  max_epochs: 1000
  learning_rate: .0005
  min_delta: .00000008
  patience: 100
  temperature: 1
  temperature_decay: .9999
  single_epoch_test_run: False
  which_data: 'R'
  nclass: 2
  n_rep: 10 # number of times to fit the model with different starting values
  N: 1000
  nitems: 20
  model: 'gs' #gs, vq or rbm
