configs:
  # general optimization parameters:
  batch_size: 32
  max_epochs: 500
  learning_rate: .0005
  min_delta: .0000008
  patience: 10
  temperature: 1
  temperature_decay: .9999
  single_epoch_test_run: False
  which_data: 'sim'
  nclass: 2
  N: 1000
  nitems: 200
  model: 'vq' #gs or vq
